name: fdark
description: Enhanced API server
version: 1.0.0
homepage: https://github.com/andypangaribuan/fdark

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  shelf: ^1.4.0
  shelf_router: ^1.1.3
  meta: ^1.8.0
  postgres: ^2.5.2
  
  fdation: ^1.0.1
  # fdation:
  #   path: /Users/apangaribuan/repo/github/fdation

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
